
spring:
  application:
    name: todoservice
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    instanceId: ${spring.application.name}:${random.value}
    preferIpAddress: true