apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
  labels:
    app: eurekaserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        -
          image: fernandochristyanto/eurekaserver
          name: eurekaserver
          ports:
            - containerPort: 8761

